### ISSUE TITLE
解决笔记/笔记本冲突

### ISSUE THREAD

**Issue by lealife** [leanote/leanote-android#10]
同步时必须先pull再push, 这样能知道冲突, 防止覆盖.

附iOS/桌面端的解决冲突方案:

笔记的冲突解决:
getSyncNotes获取服务端更新的笔记, 发现serverNote1本地修改了(localNote1), 此时发生冲突, 处理方式:

1. 将localNote1复制一份成localNote1_conflict
2. 将localNote1删除
3. 将serverNote1保存到本地

因为一般是pull时发生冲突, 那么接下来的push是否要push新复制的localNote1_conflict呢?

* iOS端确实是直接将该笔记push了, 这样服务器多了一个笔记
* 桌面端需要用户标记该笔记已解决冲突, 才能push

笔记本的冲突解决:
getSyncNotebooks获取服务端更新的笔记本, 发现serverNotebook1本地修改了(localNotebook1), 此时发生冲突, 处理方式是直接将服务端的数据覆盖本地.

**Comment by houxg** [comment]
fix by https://github.com/houxg/Leamonax/commit/16f0a54942682831c3a983b1ae3db4556f5e009f

**Comment by lealife** [comment]
大 👍
