### ISSUE TITLE
默认笔记本为已选择的笔记本

### ISSUE THREAD

**Issue by lealife** [leanote/leanote-android#12]
当选择某笔记本时, 在笔记列表里添加笔记, 应该默认笔记本为该笔记本

**Comment by houxg** [comment]
是否是这样：
1. 选择某个笔记本A，笔记列表显示A下所有笔记，点击添加，则新笔记所属笔记本为A
2. 其他情况，使用最近一次使用的笔记本

**Comment by lealife** [comment]
是的

**Comment by houxg** [comment]
@xingstarx 
fix by https://github.com/leanote/leanote-android/commit/55ca0af690615a4a1cba140b51de542f552d6aab

**Comment by lealife** [comment]
谢谢!

**Comment by xingstarx** [comment]
跟了下代码，看了下最近一次使用的笔记的逻辑，是根据数据库查询最近一次改动的note找到对应的notebook， 如果用户一直是只看不做修改笔记操作的话，这样"update_time"这个字段对应的值就没有改动的，这样查询不太好吧。

我想的是在preference里面记录最后一次操作的笔记Id。
规则如下：
每次点击浏览笔记的时候，都把noteId存到配置文件中, p.edit().put("RENCENT_NOTE_ID", "57c2a59fbe2f9623c6000001")

最终根据noteId找到对应的note,如果note == null ，那么就按照你现在的逻辑，找最近修改过的笔记； note != null , 就找到对应的notebook，获取对应的notebookId

**Comment by houxg** [comment]
我觉得我们更需要的是有个比较直观好看的方式告诉用户这个笔记放在哪儿，现在的藏得太深。
另外我期望的逻辑是
```
if (存在最近n天编辑或新建所使用的笔记本) {
    使用该笔记本
} else {
   使用默认
}
```
@lealife 
@xingstarx 
你们觉得怎么样

**Comment by lealife** [comment]
如果用户选择了某笔记本, 在该笔记本下的笔记列表中新建, 我感觉还是用该笔记本.
其它情况, 用默认

**Comment by xingstarx** [comment]
@lealife  @houxg 按照你们俩说的话，现在的逻辑就是对的，不用更改。我觉得也可以。至于说的告诉用户这个笔记放在哪？ 这个可以讨论下，放在页面哪个地方？
