### ISSUE TITLE
笔记列表下拉刷新只是pull没有push

### ISSUE THREAD

**Issue by lealife** [leanote/leanote-android#14]
有一些笔记没有按保存就回到了列表页, 此时下拉不能push到服务器. 建议增加这个功能
@houxg

**Comment by yisqiu** [comment]
确实有这个问题，我在手机上面新建了一个笔记，或者修改了一个笔记，不知道什么原因点击保存后无法同步到服务器上面（本地笔记在左下角一直显示“有变动”字样），在列表页下拉也只有从服务器下载笔记，没有上传本地变动到服务器功能
