### ISSUE TITLE
笔记文件内容很大时出现ANR问题以及黑屏

### ISSUE THREAD

**Issue by huanghuiyang** [leanote/leanote-android#16]
当文件内容很大时，点击预览模式，APP没反应，多次点击就会出现ANR问题；或者当你打开某个大文件再返回会出现黑屏，有时还会ANR

**Comment by xingstarx** [comment]
fix https://github.com/leanote/leanote-android/commit/e0e4ce83be8fa62907d35055ddb8236cadd8e5b9
