### ISSUE TITLE
自定义服务器设置中不支持特殊端口的https

### ISSUE THREAD

**Issue by YzmsLinq** [leanote/leanote-android#17]
在登录的自定义服务器设置中不支持特殊端口的https，如：https://xxx.xxx.xx.xx:4432。会一直显示“网络错误”。在桌面版上登录正常，应该不是服务器的问题。

**Comment by lealife** [comment]
自建https问题

**Comment by YzmsLinq** [comment]
@houxg 经过验证用StartCom的免费SSL证书可以登录。希望在新版中加入忽略自建SSL证书验证，谢谢！
