### ISSUE TITLE
自建服务器登录失败

### ISSUE THREAD

**Issue by yisqiu** [leanote/leanote-android#18]
自建服务器登录失败具体地址:http://xxx.xxx.xxx.xxx/wdbj 这种形式的url点击登录后没有反应（网页版和PC版本登录正常）请管理员检查一下

**Comment by xingstarx** [comment]
@lealife @houxg  这种域名形式的，我不确定对应的api是否也满足```http://xxx.xxx.xxx.xxx/wdbj/api/auth/login``` 这种形式，按照 @yisqiu 所说的，我觉得应该是请求的api的url不对，可能是```http://xxx.xxx.xxx.xxx/api/auth/login``` 这样的形式

有两个问题都说到了这个自建服务器的
#17  的问题应该也是如此

**Comment by houxg** [comment]
在输入自建服务器地址时，下方会有对应的api样例，使用者可以以此自测，没有必要拘泥于web端的地址

**Comment by YzmsLinq** [comment]
我检查过登录接口的地址是https://xxx.xxx.xxx.xxx:4432/api/login
如果用正常的http登录的话，接口地址是http://xxx.xxx.xxx.xxx:8080/api/login
两个应该没有差别，http的能登录，https的一直显示“网络错误”

**Comment by yisqiu** [comment]
@xingstarx  我看了,输入上述url地址后,下面的接口地址如下

http://xxx.xxx.xxx.xxx/wdbj/api/login

这个地址如果直接在网页url里面输入的话报404错误

**Comment by YzmsLinq** [comment]
我测试了一下http://xxx.xxx.xxx.xxx:8080/api/auth/login是可行的，验证密码

**Comment by yisqiu** [comment]
@YzmsLinq 我上面的接口里面少了一个auth,如果我加上auth就可以得到验证密码的页面
{"Ok":false,"Msg":"Wrong username or password"}

是不是aip后面少了一个auth?
http://xxx.xxx.xxx.xxx/wdbj/api/login

**Comment by YzmsLinq** [comment]
https://xxxx.xxxx.xxxx:4432/api/auth/login 也可行与http的一样出现{"Ok":false,"Msg":"用户名或密码有误"}

**Comment by houxg** [comment]
@yisqiu @YzmsLinq `/api`及之后的地址均是App自己拼接的

**Comment by yisqiu** [comment]
@houxg 就是这个原因,是不是app接口地址拼接错了?

**Comment by YzmsLinq** [comment]
问题是https://xxxx.xxxx.xxxx:4432在桌面版和网页版上登录都很正常的

**Comment by YzmsLinq** [comment]
@yisqiu 如果app接口地址拼接错了，那么也是针对特殊形式的自建 服务器，如：http://xxx.xxx.xxx.xxx/xxx或https://xxx.xxx.xxx.xxx:xxxx。因为http://xxx.xxx.xxx.xxx/及http://xxx.xxx.xxx.xxx:xxxx是正常的。

**Comment by houxg** [comment]
能否私下提供地址我们测试一下？我的邮箱是houxg09@gmail.com

**Comment by YzmsLinq** [comment]
@houxg 我测试了一下用https://xxx.xxx.xxx.xxx,也不可以。我等会儿将地址发给你。

**Comment by YzmsLinq** [comment]
@houxg 地址及用户名、密码已发，请查收。

**Comment by houxg** [comment]
` Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.`
证书问题

**Comment by YzmsLinq** [comment]
对了，桌面版第一次登录时叫我确认了一下证书。我的Seafile网盘也是做在该服务器上的，Seafile的手机客户端也叫我确认了一下证书，你们的客户端也建议提供该功能。我是自建的证书

**Comment by yisqiu** [comment]
@houxg 地址已发到邮箱,请帮忙测试,谢谢

**Comment by YzmsLinq** [comment]
![screenshot_2017-03-07-10-58-11](https://cloud.githubusercontent.com/assets/24677465/23640000/ae019216-0325-11e7-9dae-e47d6986f098.png)
