### ISSUE TITLE
Search doesn't run properly

### ISSUE THREAD

**Issue by Ardakilic** [leanote/leanote-android#25]
Hello,

The search function on Android app (self-hosted server) doesn't work properly.

E.g:

1. I added a new note "Merhaba" over mobile

![2017-03-20 08 43 16](https://cloud.githubusercontent.com/assets/2063957/24092967/3bc9dafc-0d5a-11e7-91c6-50763db4e15c.png)

2. When I type "merha", it displays (normal so far):

![2017-03-20 08 43 49](https://cloud.githubusercontent.com/assets/2063957/24092975/47d17364-0d5a-11e7-8da2-0a0e55cba1fc.png)

3. This is the home screen of leanote. Notice the default notes are still there:

![2017-03-20 08 45 22](https://cloud.githubusercontent.com/assets/2063957/24093014/788bd972-0d5a-11e7-89b0-597dfb94130f.png)

4. However, there are contents in note "merhaba", which aren't previewed (these should have be previewed in step 3):

![2017-03-20 08 46 51](https://cloud.githubusercontent.com/assets/2063957/24093042/90daff08-0d5a-11e7-937f-3cec475882ec.png)

5. Now, as you can see in step 3, even the default notes have text like "introduction", "Leanote, not just a notepad" etc.

But I can't search these contents at all!

E.g: I type notepad, and the default english note should appear (because it has a text "not just a __notepad__"), but it doesn't.

![2017-03-20 08 51 00](https://cloud.githubusercontent.com/assets/2063957/24093183/31c74642-0d5b-11e7-8bde-b64a962cba0f.png)

I type , then click the righ bottom seach icon from my keyboard, no result. This also happens with my custom notes.

I'm using version "v1.0-beta6.1". Using Lineage OS Android 7.1.1 on Oneplus 2. In desktop client, it works nicely.

I'd appreciate if this could be investigated.

Thanks in advance,

**Comment by houxg** [comment]
1. currentyly the app only support searching by title, full-text-searching is still in plan.
2. we haven't add any handler to handle keybord event, we will fix it ASAP. @xingstarx could you do that?

**Comment by Ardakilic** [comment]
Thank you, appreciate the response. Not urgent for me, I just wanted to report the issue I've encountered. Keep up the great work! 👍

**Comment by xingstarx** [comment]
If the search has no results, it will prompt Toast and hide keyboard
https://github.com/leanote/leanote-android/commit/5d433873694f32781db1c88855b9d37062614b03
