### ISSUE TITLE
建议添加启动动画

### ISSUE THREAD

**Issue by binsheng** [leanote/leanote-android#27]
# 现象
- 有账户登录过的时候，再次打开 APP 会有一个空白，之后直接跳到 MainActivity 。这样显得很突兀，用户体验不好。
# 建议
- 在 LaunchActivity 中添加背景，并等待几秒后跳转到 MainActivity。期间可以做一些简单的动画。

**Comment by xingstarx** [comment]
我看了你的的develop分支，感觉动画效果可以，欢迎提pr额 ^_^
