### ISSUE TITLE
红米Note3手机选择图片界面表现异常

### ISSUE THREAD

**Issue by fengdexunmi** [leanote/leanote-android#28]
![screenshot_2017-03-28-11-50-59-694_com leanote android](https://cloud.githubusercontent.com/assets/2813239/24391379/55817cc6-13c1-11e7-98b7-43eb1945eb75.png)

如上图所示
测试手机：红米Note3 / Android 5.0.2 / MIUI 8 7.3.23

- 当相册里面没有图片的时候，点击“所有图片”不应该弹出popupwindow或者提示相册中没有照片
- 红米手机上，点击“所有图片”的时候，背景颜色会变成黑色  

开始我想提交Pull request，发现这里是采用第三方的图片选择器，fork了leanote-android的代码也没有办法修改，于是就来这里提交下issue，谢谢~
（我单独clone了这个第三方图片选择器库并运行，发现它最新的版本还是会存在这个问题，初步判断是红米手机上面针对ListPopwindow设置背景色有问题）

**Comment by xingstarx** [comment]
我用自己的两台红木设备测试了下,红米3/Android 5.1 MIUI7 效果正常，背景颜色效果也还不错；红米2A/Android 4.4.4 MIUI7 这个背景颜色看不出来，感觉也没有你这种情况。我也编译运行了 https://github.com/smuyyh/ImageSelector 结果和leanote-android的是一致的。

popupwindow用的是support v7包下面的 ListPopupWindow。

具体还得你到ImageSelector这个项目下给作者提个issue额。 我这边没有你这样的设备。
