### ISSUE TITLE
安卓7.0同步文件失败

### ISSUE THREAD

**Issue by freedeaths** [leanote/leanote-android#40]
自建server
蚂蚁笔记版本：v1.0-beta.7 安卓APP来自官方release
手机：华为P10，EMUI5.1，Android 7.0
问题：
    PC端网页和客户端都可以正常工作；
    安卓手机端网页可正常工作，APP可以正常登录，但是无法同步，笔记始终显示不了任何一条，下拉显示同步笔记失败。

**Comment by freedeaths** [comment]
刚还测试了乐视手机，安卓6.0，同样问题。

**Comment by Ericwyn** [comment]
应该是忘了加入动态权限申请代码来适配Android 6.0 以上的新特性，暂时的解决方法是手动给予 应用 存储空间 、电话、和相机 权限就好了
