### ISSUE TITLE
标题被占入了很多 html显得混乱

### ISSUE THREAD

**Issue by daidaiworm** [leanote/leanote-android#42]
![_20170719132235](https://user-images.githubusercontent.com/3594904/28351876-5944032a-6c85-11e7-9d41-79a5c56f80ef.jpg)

原始文档好像是 印象笔记导入

安卓手机上操作，当把正文的一部分复制到想要成为标题，就出现html代码了。

**Comment by xingstarx** [comment]
多谢反馈，已确认，是有这个问题。今晚在修复额。。
