### ISSUE TITLE
建议(Android端)

### ISSUE THREAD

**Issue by githubwzb** [leanote/leanote-android#47]
Markdown预览时，无法横向移动导致超长的Mathjax语句只能显示一部分。
PC(Win)端也有这种情况，但可以通过调节编辑框和预览框的中介线解决。
希望问题早日解决。

**Comment by xingstarx** [comment]
能否给一个例子，就是说你说的那个超长的Mathjax语句呢，方便我调试呢

**Comment by githubwzb** [comment]
$$
\begin{align}
\overrightarrow{AD} 
&= \overrightarrow{AB} + \overrightarrow{BD} \\
&= \overrightarrow{AB} + \frac {|\overrightarrow{BD}|} {|\overrightarrow{BC}|} \overrightarrow{BC} \\ 
&= \overrightarrow{AB} + \frac {|\overrightarrow{BD}|} {|\overrightarrow{BC}|}(\overrightarrow{AC}-\overrightarrow{AB}) \\
&= \frac {|\overrightarrow{CD}|} {|\overrightarrow{BC}|} \overrightarrow{AB} + \frac {|\overrightarrow{BD}|} {|\overrightarrow{BC}|} \overrightarrow{AC}
\end{align}
$$

**Comment by githubwzb** [comment]
手机屏幕有点小，蚂蚁笔记又没有横屏模式
又不支持横向滚动，只要等式一长，就不能显示了，被屏幕给“吞了”。

**Comment by githubwzb** [comment]
版本v1.0-beta.7(怀疑是盗版)

**Comment by xingstarx** [comment]
预估一个月解决，给自己先挖个坑

**Comment by xingstarx** [comment]
https://github.com/leanote/leanote-android/commit/3da951f9afc48d70554f5f52e8d5ad758a1a285f 先弄成横竖屏切换的形式O__O "…
