### ISSUE TITLE
emoji支持为何如此差?

### ISSUE THREAD

**Issue by githubwzb** [leanote/leanote-android#48]
很抱歉有给程序员同志添麻烦了(偷笑ing)
但是我实在是受不了了。😒
这是emoji，"😖"这是另外一个，这是一堆emoji
😂😂😃😄👿😉😊😌😍😏😒😖😖😘😜😝😞😠😡😢😣😱😲😲😭😪😨😳🙃😋😗😛🤑🤓🤓😎🤗🙄😤🤐🤐🤒🤒😴👯👶👦👧👧👨👨👩👫👫👱👲👳👴👴👵👵👮👷👷👸💂👼🎅👻💩💀👽👾💁🙅🙆💆💇💇🙋🙇🙇👫💑💏🙌👏👂👀👃👄💋💅👋👍👎👆👇👈👉✌👊💪👐👐🍀🌴🌷🌸🌹🌺🌺🌻💐🌾🍁🍂🍃🐭🐹🐹🐮🐰🐰🐎🐴🐑🐔🐤🐦🐧🐘🐗🐗🐷🐶🐺🐻🐨🙈🙉🙊🐒🐍🐳🐬🐟🐠🐠🐚🐛🐾🌚🌝🌛🌜🌜🌞⚡⚡🔥🌙☁💦☔☔💨🌟⭐🌄🌅🌈🌊🗻🍅🍆🍉🍎🍓🍔🍘🍚🍚🍜🍝🍞🍟🍡🍢🍣🍦🍧🍱🍲🍲🍳🍵☕🍶🍺🍻🍸🎀🎁🎂🎃🎄🎍🎑🎆🎇✨🎓👑🎎🎏🎐🎌💍💍💔💕💞💓💗💖💘💝💟💜💛💚🏃🚶💃🏊🏄🛀🎿⛄⚽🏀🏈⚾🎾⛳🏆🏁🎸🎷🎺🎵🎵🎶🎧🎤🎩🎬🎨🎯🎱🎰🀄🎡🎢🚃🚅🚅🚇🚌🚌🚑🚒🚓🚕🚗🚙🚚🚲🚏⛽🚧🚥🚀✈💺🚢🚤⛵🗼⛲🏰🏯🌇🌆🌃🏢🏬🏭🏣🏥🏦🏨🏩💒⛪🏪🏫🔞🉐㊙㊗🈵🈶🈸🈺🈹🈳🈂🈁🈯🈯✳🆚🅰🅾🅾🆔🅿🚾🆕🆗🏧♈♉♊♋♌♍♎♏♐♒♓🚻🚹🚺🚺🚼♿🚭▶⏩⏪➡⬅⬆⬇↗↘↙#⃣0⃣0⃣1⃣2⃣3⃣5⃣6⃣7⃣7⃣8⃣8⃣9⃣🎦™©®💱➿〽❗❓❕❔❌⭕💯🔝🌀⛎🔰🔱⚠♨💢♠♣♥⬜📣📢🔊💤🔔🕐🕑🕒🕓🕔🕔🕕🕖🕗🖥📷🎥📻📠💾💿📀📼💡📡💎🌂🌂👜💼🎒👡👡👠👠👢👞👙👘👚👔🚽💈💉💊🔨💣🚬🔫📮📬✂🔍🔒🔓🔑🇨🇳🇫🇷🇮🇹🇯🇵🇰🇷🇬🇧🇰🇷🇺🇸🔗🖇️📐✒🔐

然而这么丰富的表达库竟然绝大部分无法显示，多么让人心塞！

求更新，求解决！

**Comment by githubwzb** [comment]
github上有免费开源的emoji库。

**Comment by githubwzb** [comment]
可以参考这一个
https://github.com/vanniktech/Emoji

**Comment by houxg** [comment]
emoji目前没有专门做适配，所以是完全基于webview的支持程度，所以。。。试试升级手机？（逃
说回来，我们会考虑加上这一支持， 也欢迎提交pr，也许会更快一点

**Comment by houxg** [comment]
Pixel2 PQ1A.181205.002测试，大部分emoji已经支持，如果有个别emoji还未支持的，请提交新的issue
