### ISSUE TITLE
Android 7.1.2 上面动态权限申请失败

### ISSUE THREAD

**Issue by Ericwyn** [leanote/leanote-android#51]
自建服务
手机型号：小米 6
系统：原生 Android 7.1.2
软件版本：v1.0-beta.7 
问题：无法实现动态权限申请，以至于软件运行的时候没有获得存储空间使用权限，导致无法正常的同步笔记。issues #40 似乎也是同样的问题。现阶段的解决方法是手动给予权限。希望增加以下动态权限申请的代码

**Comment by xingstarx** [comment]
thk
