### ISSUE TITLE
上传图片可否支持原图等比缩放

### ISSUE THREAD

**Issue by vomobile** [leanote/leanote-android#53]
上传图片可否支持原图等比缩放，而不是现在的1：1截取

**Comment by houxg** [comment]
@xingstarx 需要修改引用的第三方库ImageSelector，增加一个功能：固定宽度，高度按比例缩放
https://github.com/smuyyh/ImageSelector/blob/20ae11f48bb4834705a2992800a3e3fdd8f46bc2/library/src/main/java/com/yuyh/library/imgsel/ui/ISListActivity.java#L196
在这个位置改

**Comment by xingstarx** [comment]
(⊙v⊙)嗯 可以试试

**Comment by houxg** [comment]
打开编辑之前获取图片比例，然后传过去？

**Comment by xingstarx** [comment]
不是，是在imageSelector中做的，选中图片后，在ISListActivity获取到图片的path,可以算出图片的真实的宽和高,然后在计算出相应改传递的参数到com.android.camera.action.CROP所对应的activity中
