### ISSUE TITLE
无法上传图片

### ISSUE THREAD

**Issue by vomobile** [leanote/leanote-android#57]
版本：leanote-android-2018-01-10-v1.0-beta.8 

笔记编辑时选择图片，然后出现白屏一闪即过后内容里没有图片信息。

**Comment by xingstarx** [comment]
你详细描述下步骤，我猜测是因为2017年1月16号赠送的付费账号到期了，服务器端返回的总是`{"Ok":false,"Msg":"NEED-UPGRADE-ACCOUNT"}` 
而客户端没有做处理，也就是说客户端只能浏览笔记了

**Comment by vomobile** [comment]
我用的是自己搭建的服务器，之前的beta7可以上传图片，现在桌面版可以上传图片，但是beta8笔记编辑时选择图片，然后出现白屏一闪即过后内容里没有图片信息。

**Comment by xingstarx** [comment]
哦哦，好吧，我看看

**Comment by Ericwyn** [comment]
嗯，我设备上面leanote也会，beta8版本，在手机编辑笔记时候选择图片插入会报`                                                                     android.os.FileUriExposedException: file:///storage/emulated/0/DCIM/test.jpg exposed beyond app through Intent.getData()`，之前的版本倒是没有测试过

**Comment by vomobile** [comment]
OnePlus 5
H2OS 3.5.0（Android 7.1.1）

**Comment by xingstarx** [comment]
哦哦，大致知道是什么原因了，晚上改😂😂

**Comment by vomobile** [comment]
可否把图片改成自行选择区域，默认等比压缩，而非现在的1：1的正方形？

**Comment by xingstarx** [comment]
@vomobile 这个我暂时不知道改怎么改，你有没有可以参考的app呢？

**Comment by xingstarx** [comment]
fix in https://github.com/leanote/leanote-android/commit/2a65f13ae6adf511c16aa1ebb23a21d0a0a299c8
