### ISSUE TITLE
也在开发Android端，寻求支持

### ISSUE THREAD

**Issue by tsy12321** [leanote/leanote-android#59]
hi 我也在开发leanote android端 现在账户要升级 忘寻求支持。

github：https://github.com/tsy12321/LeanoteAndroid

微信联系方式：tsy12321

![image](https://user-images.githubusercontent.com/9690656/35204706-e811b8a4-ff6a-11e7-8252-09986c447b60.png)

![image](https://user-images.githubusercontent.com/9690656/35204717-f8623292-ff6a-11e7-96cb-c5ac63682f34.png)

![image](https://user-images.githubusercontent.com/9690656/35204721-fdcbedae-ff6a-11e7-99de-0a130b93f029.png)

![image](https://user-images.githubusercontent.com/9690656/35204728-05446a3e-ff6b-11e7-9965-559ee8629377.png)

![image](https://user-images.githubusercontent.com/9690656/35204731-0ac5d7e0-ff6b-11e7-912f-ebb2a251450b.png)

![image](https://user-images.githubusercontent.com/9690656/35204741-10e028ec-ff6b-11e7-8e71-4a4f86289372.png)

**Comment by vomobile** [comment]
👍👍👍

**Comment by tsy12321** [comment]
还没开发完，现在再调用接口都提示要升级账户了

**Comment by Ericwyn** [comment]
@tsy12321 你不是使用自己搭建的服务么？

**Comment by tsy12321** [comment]
不是 用的leanote的。

前一段时间弄了一部分，现在捡起来准备把第一版完善下发布，发现账号要升级。。。。。

**Comment by vomobile** [comment]
@tsy12321 是因为Leanote收费了，免费期过了以后要付费升级才能用吧？

**Comment by tsy12321** [comment]
恩。感谢小伙伴 @Ericwyn 提供了他部署的服务器。我在他那个上面开发测试了

**Comment by vomobile** [comment]
@tsy12321 我也是自己搭建的服务器，刚想说可以给你测试用用，Android端目前的确需要很多完善的地方

**Comment by xingstarx** [comment]
@vomobile 精力有限啊😂😂

**Comment by vomobile** [comment]
@xingstarx 明白明白，没有贬义，非常感谢各位的付出，希望这个平台能越来越好！

**Comment by xingstarx** [comment]
@vomobile (⊙v⊙)嗯 好了，issue我关了啊
