### ISSUE TITLE
App crashes when typing specific characters

### ISSUE THREAD

**Issue by csyuanc** [leanote/leanote-android#60]
Hi, thanks for developing this useful app, I've found a searching bug

If I just typed '+', '\*', or '?' in the searching block, the app would crash immediately.
However, if I typed something else first, for example, 'a+', 'a*', or 'a?', the app wouldn't crash.

This is not a big issue, I just found it accidentally. Thanks.

```
Platform info:
Device: Asus Zenfone 3 ZE520KL
OS: Android 7.0
```

**Comment by xingstarx** [comment]
okey, I will fix it soon

**Comment by xingstarx** [comment]
why did you use '*'or'+'or'?' to search note? 

'*' '+' '?' symbol are special character in Java Regex

so I suggest not to ues these symbol to search note
