### ISSUE TITLE
安卓客户端和PC客户端同步笔记失败

### ISSUE THREAD

**Issue by zingsman** [leanote/leanote-android#61]
开始服务器一直是好的，没做任何操作，突然就同步失败：
报错日志：
![image](https://user-images.githubusercontent.com/29135385/35433209-8796b014-02bd-11e8-911b-8e8f1b77efe7.png)
备注：我是自建服务器

**Comment by xingstarx** [comment]
是服务器的http转发到https出现的问题，跟客户端没有关系
