### ISSUE TITLE
PC端能正常显示图片，APP端不能（cookie问题）

### ISSUE THREAD

**Issue by OnlyCastiel** [leanote/leanote-android#63]
APP端登录，加载笔记中的图片时，request请求没有cookie，无法加载图片
PC通过浏览器访问时，登录后，加载图片，reques请求包含cookie，可以正常加载图片

**Comment by OnlyCastiel** [comment]
已找到问题：
conf/app.conf的site.url中配置的是 http://ip:port  而登录APP填写的地址是 http://ip
但是并不明白为什么这个配置会导致图片无法显示（文字可以正常显示）

**Comment by houxg** [comment]
@OnlyCastiel 请试试在App登录时填写完整的，带端口号的地址

**Comment by OnlyCastiel** [comment]
@houxg 我是把服务器的site.url去掉了端口号，然后清除了APP的缓存数据后，重新用http://ip登录就好了

**Comment by ziloeng** [comment]
一定要改site.url去掉了端口号吗？这边机器的80端口有其它服务在用了~

**Comment by Ericwyn** [comment]
@ziloeng 你可以了解一下反向代理啊～
