### ISSUE TITLE
点击编辑按钮以后到读取文本的那段时间点击相同位置会清空内容

### ISSUE THREAD

**Issue by ajacker** [leanote/leanote-android#65]
在安卓端，点击右上角的编辑按钮，会加载一下再出文字，但是右上角相同的按钮会马上变成保存，之前因为双击了两次编辑按钮（实际上是编辑和保存），因为还没来得急加载出来，所以会保存空白文本，导致缩写的笔记内容丢失

具体解决方案我觉得可以让加载完文本内容以后再出现按钮，或者是加载完文本内容之前如果按按钮发生变化了的话就让按钮被禁用，直到加载完毕以后在让按钮变成激活状态

**Comment by xingstarx** [comment]
https://github.com/leanote/leanote-android/commit/f0e43612fa931b8b8aab89870183fb31c31ecb56

**Comment by xingstarx** [comment]
目前是加载完后才能点击，废弃了之前的方案
