### ISSUE TITLE
sharing via app

### ISSUE THREAD

**Issue by MacsKavana** [leanote/leanote-android#67]
Hi,

I have installed the v1.0-beta.8.

All is fine except when I want to share some content (i.e. an URL) the app isn't in the list of possible targets (there is the mail client, google keep, messenger, etc. but not this app).

Can you fix this please?

**Comment by MacsKavana** [comment]
Yes this is what I meant (I want to replace Google Keep with Leanote and I need the android app to share the content).

**Comment by xingstarx** [comment]
Okey,I will do it .

**Comment by xingstarx** [comment]
https://github.com/leanote/leanote-android/commit/d25558c7da5471d472049fc2d2fe79cb391f57f6 Support share content to Leanote

Only support text don't support pictures
