### ISSUE TITLE
Travis/Bugly配置

### ISSUE THREAD

**Issue by houxg** [leanote/leanote-android#7]
- 修改travis release配置
- 申请并修改bugly配置

**Comment by lealife** [comment]
我不知道配

**Comment by xingstarx** [comment]
额，项目组成员应该也可以修改travis配置的吧， bugly的也好弄，看看文档就好了

**Comment by houxg** [comment]
按理说用owner的token会方便一些，也能避免不必要的麻烦。不过如果不用git release，用其他分发的话那随便一个成员就可以搞

**Comment by xingstarx** [comment]
哦，这个不清楚，还是你来吧 @houxg

**Comment by lealife** [comment]
好, token之类的我来管吧

**Comment by lealife** [comment]
@xingstarx 加我QQ 289981565
