### ISSUE TITLE
android save failed by return "noteIdNotExists"

### ISSUE THREAD

**Issue by deepnight36** [leanote/leanote-android#70]
i can update and new note via mac/win client, but failed to use android (latest release v1.0-beta.8.2)..
When i click save, system prompts "noteIdNotExists"

Following are the request data from android app:

POST /api/note/updateNote?token=5b0173f9394ab67394000002 HTTP/1.1
content-type : multipart/form-data; boundary=cb7a276c-2289-4d51-8806-0a31fa55fbd0
content-length : 2172
Host : n.hzhfzx.com
connection : Keep-Alive
accept-encoding : gzip
user-agent : okhttp/3.5.0
request body

--cb7a276c-2289-4d51-8806-0a31fa55fbd0 Content-Disposition: form-data; name="NoteId" Content-Transfer-Encoding: binary Content-Type: multipart/form-data; charset=utf-8 Content-Length: 24 5b0174a6394ab67394000004 --cb7a276c-2289-4d51-8806-0a31fa55fbd0 Content-Disposition: form-data; name="Usn" Content-Transfer-Encoding: binary Content-Type: multipart/form-data; charset=utf-8 Content-Length: 6 200274 --cb7a276c-2289-4d51-8806-0a31fa55fbd0 Content-Disposition: form-data; name="NotebookId" Content-Transfer-Encoding: binary Content-Type: multipart/form-data; charset=utf-8 Content-Length: 24 5b010e0c394ab668a800001b --cb7a276c-2289-4d51-8806-0a31fa55fbd0 Content-Disposition: form-data; name="CreatedTime" Content-Transfer-Encoding: binary Content-Type: multipart/form-data; charset=utf-8 Content-Length: 24 2018-05-20T21:14:14.000Z --cb7a276c-2289-4d51-8806-0a31fa55fbd0 Content-Disposition: form-data; name="Content" Content-Transfer-Encoding: binary Content-Type: multipart/form-data; charset=utf-8 Content-Length: 46 <p>TEst New</p><p>TEs</p><p>xjkxkxjxnt nww</p> --cb7a276c-2289-4d51-8806-0a31fa55fbd0 Content-Disposition: form-data; name="IsTrash" Content-Transfer-Encoding: binary Content-Type: multipart/form-data; charset=utf-8 Content-Length: 1 0 --cb7a276c-2289-4d51-8806-0a31fa55fbd0 Content-Disposition: form-data; name="IsMarkdown" Content-Transfer-Encoding: binary Content-Type: multipart/form-data; charset=utf-8 Content-Length: 1 0 --cb7a276c-2289-4d51-8806-0a31fa55fbd0 Content-Disposition: form-data; name="Title" Content-Transfer-Encoding: binary Content-Type: multipart/form-data; charset=utf-8 Content-Length: 8 Test New --cb7a276c-2289-4d51-8806-0a31fa55fbd0 Content-Disposition: form-data; name="IsBlog" Content-Transfer-Encoding: binary Content-Type: multipart/form-data; charset=utf-8 Content-Length: 1 0 --cb7a276c-2289-4d51-8806-0a31fa55fbd0 Content-Disposition: form-data; name="UpdatedTime" Content-Transfer-Encoding: binary Content-Type: multipart/form-data; charset=utf-8 Content-Length: 24 2018-05-20T21:38:07.684Z --cb7a276c-2289-4d51-8806-0a31fa55fbd0--

response header

**Comment by xingstarx** [comment]
Are you custom server？

**Comment by deepnight36** [comment]
Yes, i just setup my server based on the latest release version.

**Comment by xingstarx** [comment]
https://github.com/leanote/leanote-android/issues/64
I think this problem come from  the server side， I do not know how to solve the problem

**Comment by baivoom** [comment]
同样的问题, 当把数据库迁移到另一个服务器时, 一直出现这个问题, 但是奇怪的是, 用浏览器来使用是没有问题的, 问题只存在于android端

**Comment by baivoom** [comment]
OK, 我猜测是ANDROID端与最新的leanote服务端代码不兼容.

**Comment by xingstarx** [comment]
O__O "… 这个不知道额，也不好测试啊

**Comment by Svarto** [comment]
Hi All, great job on leanote! Any update on this issue? I ran into the same problem with a self-hosted server, anyone solved this?

**Comment by houxg** [comment]
hi @Svarto , I'm going to work on this case. however, I don't have a custom server. could you provide me one? you can send the server url and port to houxg09@gmail.com. thanks

**Comment by Svarto** [comment]
Actually, I managed to fix this. I had used the source dev install, but when I switched over to binary version then this error disappeared. Thanks for the quick support!!

**Comment by deepnight36** [comment]
Still not know why?

**Comment by cybershaman** [comment]
I am also encountering this problem with a self-hosted Leanote install. Only happens with Android app, not with iOS or Web client. I managed to temporarily circumvent this issue by deleting the initial first Leanote note "About Leanote" but the problem is back again.

@houxg do you want an account on my self-hosted installation to look into this?

**Comment by 1391518** [comment]
服务端使用Docker部署, 镜像版本使用jim3ma/leanote:alpine-2.6.1, 安卓客户端使用v1.0-beta.8.5.
保存时,同样提示"noteIdNotExists".
把镜像版本降至jim3ma/leanote:alpine-2.6, 保存正常.
