### ISSUE TITLE
SSL connection problem

### ISSUE THREAD

**Issue by MacsKavana** [leanote/leanote-android#71]
I have a self hosted Leanote instance with nginx + SSL (Let's Encrypt).
SSL works from browser but from the Android app I always get a "Network error" message.
When I disable SSL I can connect the app to Leanote.
Additionally when the "Network error" message appears the "Sign in" button disappears (keeps spinning) but the spinner can be clicked.

App version: v1.0-beta.8.3

**Comment by hengbo12345** [comment]
i am facing same problem. 
can anyone help solve it?

**Comment by xingstarx** [comment]
@MacsKavana @hengbo12345 Can you two give me a test account?
If you can, please send me an email to xxx823952375@gmail.com

**Comment by xingstarx** [comment]
@hengbo12345 
@MacsKavana thanks,I Fixed this issue on https://github.com/leanote/leanote-android/releases/tag/v1.0-beta.8.4
you can download v1.0-beta.8.4, try it

**Comment by MacsKavana** [comment]
Hi,

New version is working fine.

Thank you.

**Comment by xingstarx** [comment]
You are welcome.
