### ISSUE TITLE
反应多个BUG

### ISSUE THREAD

**Issue by runningpig6666** [leanote/leanote-android#74]
1.win环境桌面端编辑XML，输入带有style的标签，输入后保存，然后切换别的文档，再返回刚保存的文档，会返现带有style的XML代码段空白。如下图，好吧不能放图，BUG代码放上来
ProgressBar style="?android:attr/progressBarStyleHorizontal"请自动在内容左右加<   和   />，这里加上评论显示不全
只要输入这种XML，然后保存，切换一下视图，回来看一定显示空白。
2.插入相同像素的图片，编辑时调整大小为200宽，按理说两张图片并排显示应该显示相同的大小，然后经常会出现显示大小不一致的问题。我已经找到了解决办法，就是一张一张的插入，调整好一张再放另一张，最后把图片放一行，显示的大小才相同。
3.选择要输入的代码语言后，出现的那个输入横条，按删除键，有时候可以删除，有时候按很多遍都无法删除。
4.还有很多BUG，都是小问题，比如只回车一次，却空格2行等。希望把第一个问题解决，别的不重要。
<ProgressBar style="?android:attr/progressBarStyleHorizontal"/>

**Comment by xingstarx** [comment]
第一个问题，不是windows的么，你怎么反馈到Android 上了啊

**Comment by runningpig6666** [comment]
这些问题都是windows桌面的问题。因为找不到别的留言的地方，最后看到这里好像可以反馈。非常感谢作者提供这样的软件很好用，就是第一个BUG一定要修复一下。

**Comment by xingstarx** [comment]
O__O "… 我不是作者额，windows的向我反馈没用额，我看不懂代码额，我只看Android的.

在这个地方反馈，https://github.com/leanote/desktop-app/issues

**Comment by xingstarx** [comment]
默认就是竖屏啊，只有一个页面是支持横屏的😂😂
学Android的话，还是多看书，多实践额

**Comment by runningpig66** [comment]
是完全不支持横屏。我将手机横过来以后，软件会跟着横过来半秒，然后立马回到竖屏。

**Comment by xingstarx** [comment]
哦哦，你这样说是的，的确不支持横屏，很多app都不支持横屏，感觉竖屏就可以了

**Comment by runningpig66** [comment]
希望加入横屏模式，因为我是用来在电脑端做代码笔记的。在手机上看的时候，因为代码的行过长，手机上总是会换行，显示效果会很不好。如果软件可以横过来显示，显示效果就和电脑上一样啦。横屏看起来就像是在Android studio中看源码的效果一样，代码缩进很清晰。

**Comment by xingstarx** [comment]
![image](https://user-images.githubusercontent.com/8245264/41216393-c2aa2aa8-6d86-11e8-8ae5-06089289ca17.png)
看到这个页面了么，这个预览笔记的页面，旋转功能就可以进行横竖屏切换的。
最新的apk地址是https://github.com/leanote/leanote-android/releases/download/v1.0-beta.8.5/Leanote.apk
