### ISSUE TITLE
gradle sync 失败：Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.android.support:design:26.1.0.

### ISSUE THREAD

**Issue by gykimo** [leanote/leanote-android#76]
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.android.support:design:26.1.0.

Could not resolve com.android.support:design:26.1.0.
Required by:
    project :app
 > Could not resolve com.android.support:design:26.1.0.
    > Could not get resource 'http://maven.aliyun.com/nexus/content/repositories/jcenter/com/android/support/design/26.1.0/design-26.1.0.pom'.
          > Could not GET 'http://maven.aliyun.com/nexus/content/repositories/jcenter/com/android/support/design/26.1.0/design-26.1.0.pom'.
                   > Can't connect to SOCKS proxy:Connection refused (Connection refused)

**Comment by houxg** [comment]
use jcenter please

**Comment by gykimo** [comment]
Hi，其实一开始我就使用的jcenter，错误一样：
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.android.support:appcompat-v7:26.1.0.

Could not resolve com.android.support:appcompat-v7:26.1.0.
Required by:
    project :app
 > Could not resolve com.android.support:appcompat-v7:26.1.0.
    > Could not get resource 'https://jcenter.bintray.com/com/android/support/appcompat-v7/26.1.0/appcompat-v7-26.1.0.pom'.
          > Could not GET 'https://jcenter.bintray.com/com/android/support/appcompat-v7/26.1.0/appcompat-v7-26.1.0.pom'.
                   > Can't connect to SOCKS proxy:Connection refused (Connection refused)
