### ISSUE TITLE
自建服务器,Android无法同步笔记

### ISSUE THREAD

**Issue by liuzhongcool** [leanote/leanote-android#80]
App版本:v1.0-beta.7
服务器正常WEB访问,桌面端(Mac)正常使用.

**Comment by liuzhongcool** [comment]
服务器走的HTTPS,Android端都默认打开'我的博客'是HTTP,请作者确认下.

**Comment by xingstarx** [comment]
用这个版本试试呢 https://github.com/leanote/leanote-android/releases/tag/v1.0-beta.8.4
