### ISSUE TITLE
安卓客户端无法push数据

### ISSUE THREAD

**Issue by widy21** [leanote/leanote-android#91]
安卓系统版本：8.1.0
leanote安卓版本安装的官网最新版
leanote服务器是自己搭建在云服务器上的
在安卓手机上新建、编辑、保存的笔记，并没有push到云端，点击保存时，在手机底部弹出“notebookIdNotExists"
刷新网页端、pc端，并没有发现安卓上新建或编辑的笔记内容
但是从网页端、pc端新建或编辑的笔记内容，在安卓端下拉刷新后，能正常显示
根据以前的issue，给安卓应用打开了手机的所有权限，问题依旧存在

**Comment by xingstarx** [comment]
麻烦在你的leanote服务器上，帮我创建个测试账号，发我邮箱，我帮你调试验证下 xxx823952375#gmail.com

**Comment by widy21** [comment]
> 麻烦在你的leanote服务器上，帮我创建个测试账号，发我邮箱，我帮你调试验证下 xxx823952375#gmail.com

**Comment by widy21** [comment]
@xingstarx 已发送，请查收。

**Comment by xingstarx** [comment]
#70
